// Known merchants, matched against the RAW uppercase bank string.
// [pattern, displayName, emoji, category]
// Categories: Food delivery, Restaurants, Coffee, Groceries, Shopping,
// Subscriptions, Transport, Gas, Travel, Entertainment, Fitness,
// Self-care, Drinks, Gaming, Tech, Money sent, Other

export const MERCHANTS = [
  // Food delivery
  [/DOORDASH|DD \*DOORDASH/, 'DoorDash', '🛵', 'Food delivery'],
  [/UBER\s*\*?EATS|UBEREATS/, 'Uber Eats', '🛵', 'Food delivery'],
  [/GRUBHUB/, 'Grubhub', '🛵', 'Food delivery'],
  [/POSTMATES/, 'Postmates', '🛵', 'Food delivery'],
  [/INSTACART/, 'Instacart', '🛒', 'Groceries'],

  // Coffee
  [/STARBUCKS/, 'Starbucks', '☕', 'Coffee'],
  [/DUNKIN/, "Dunkin'", '☕', 'Coffee'],
  [/BLUE BOTTLE/, 'Blue Bottle Coffee', '☕', 'Coffee'],
  [/PEET'?S/, "Peet's Coffee", '☕', 'Coffee'],

  // Restaurants / fast food
  [/MCDONALD/, "McDonald's", '🍔', 'Restaurants'],
  [/CHIPOTLE/, 'Chipotle', '🌯', 'Restaurants'],
  [/CHICK-?FIL-?A/, 'Chick-fil-A', '🍗', 'Restaurants'],
  [/TACO BELL/, 'Taco Bell', '🌮', 'Restaurants'],
  [/WENDY'?S/, "Wendy's", '🍔', 'Restaurants'],
  [/BURGER KING/, 'Burger King', '🍔', 'Restaurants'],
  [/DOMINO'?S/, "Domino's", '🍕', 'Restaurants'],
  [/PIZZA HUT/, 'Pizza Hut', '🍕', 'Restaurants'],
  [/PAPA JOHN/, "Papa John's", '🍕', 'Restaurants'],
  [/\bSUBWAY\b/, 'Subway', '🥪', 'Restaurants'],
  [/PANERA/, 'Panera', '🥖', 'Restaurants'],
  [/FIVE GUYS/, 'Five Guys', '🍔', 'Restaurants'],
  [/SHAKE SHACK/, 'Shake Shack', '🍔', 'Restaurants'],
  [/IN-?N-?OUT/, 'In-N-Out', '🍔', 'Restaurants'],
  [/PORTILLO/, "Portillo's", '🌭', 'Restaurants'],
  [/CULVER'?S/, "Culver's", '🍦', 'Restaurants'],
  [/RAISING CANE/, "Raising Cane's", '🍗', 'Restaurants'],
  [/PANDA EXPRESS/, 'Panda Express', '🥡', 'Restaurants'],
  [/WINGSTOP/, 'Wingstop', '🍗', 'Restaurants'],
  [/SONIC DRIVE/, 'Sonic', '🍔', 'Restaurants'],

  // Groceries
  [/WHOLE\s*FOODS|WHOLEFDS/, 'Whole Foods', '🛒', 'Groceries'],
  [/TRADER JOE/, "Trader Joe's", '🛒', 'Groceries'],
  [/\bKROGER\b/, 'Kroger', '🛒', 'Groceries'],
  [/SAFEWAY/, 'Safeway', '🛒', 'Groceries'],
  [/\bALDI\b/, 'Aldi', '🛒', 'Groceries'],
  [/JEWEL-?OSCO|JEWEL OSCO/, 'Jewel-Osco', '🛒', 'Groceries'],
  [/HY-?VEE/, 'Hy-Vee', '🛒', 'Groceries'],
  [/PUBLIX/, 'Publix', '🛒', 'Groceries'],
  [/WEGMANS/, 'Wegmans', '🛒', 'Groceries'],
  [/H-E-B|HEB ONLINE/, 'H-E-B', '🛒', 'Groceries'],

  // Big box / shopping
  [/AMZN|AMAZON/, 'Amazon', '📦', 'Shopping'],
  [/\bTARGET\b|TARGET\.COM|TARGET 000/, 'Target', '🎯', 'Shopping'],
  [/WAL-?MART|WM SUPERCENTER/, 'Walmart', '🛍️', 'Shopping'],
  [/COSTCO/, 'Costco', '🛍️', 'Shopping'],
  [/\bCVS\b/, 'CVS', '💊', 'Shopping'],
  [/WALGREENS/, 'Walgreens', '💊', 'Shopping'],
  [/7-ELEVEN|7 ELEVEN/, '7-Eleven', '🏪', 'Shopping'],
  [/HOME DEPOT/, 'Home Depot', '🔨', 'Shopping'],
  [/LOWE'?S/, "Lowe's", '🔨', 'Shopping'],
  [/\bIKEA\b/, 'IKEA', '🪑', 'Shopping'],
  [/\bETSY\b/, 'Etsy', '🧶', 'Shopping'],
  [/\bEBAY\b/, 'eBay', '🛍️', 'Shopping'],
  [/SHEIN/, 'Shein', '👗', 'Shopping'],
  [/\bTEMU\b/, 'Temu', '🛍️', 'Shopping'],
  [/ALIEXPRESS/, 'AliExpress', '🛍️', 'Shopping'],
  [/\bNIKE\b/, 'Nike', '👟', 'Shopping'],
  [/LULULEMON/, 'Lululemon', '🧘', 'Shopping'],
  [/OLD NAVY/, 'Old Navy', '👕', 'Shopping'],
  [/\bZARA\b/, 'Zara', '👗', 'Shopping'],
  [/H&M|H & M/, 'H&M', '👕', 'Shopping'],
  [/SEPHORA/, 'Sephora', '💄', 'Self-care'],
  [/\bULTA\b/, 'Ulta', '💄', 'Self-care'],
  [/BARNES\s*&\s*NOBLE|BARNES AND NOBLE/, 'Barnes & Noble', '📚', 'Shopping'],

  // Subscriptions / streaming / software
  [/NETFLIX/, 'Netflix', '📺', 'Subscriptions'],
  [/SPOTIFY/, 'Spotify', '🎧', 'Subscriptions'],
  [/\bHULU\b/, 'Hulu', '📺', 'Subscriptions'],
  [/DISNEY\s*(PLUS|\+)/, 'Disney+', '📺', 'Subscriptions'],
  [/HBO|MAX\.COM/, 'Max', '📺', 'Subscriptions'],
  [/PARAMOUNT\+|PARAMOUNT PLUS/, 'Paramount+', '📺', 'Subscriptions'],
  [/PEACOCK/, 'Peacock', '📺', 'Subscriptions'],
  [/YOUTUBE\s*(PREMIUM|TV)?|GOOGLE \*YOUTUBE/, 'YouTube', '📺', 'Subscriptions'],
  [/AUDIBLE/, 'Audible', '🎧', 'Subscriptions'],
  [/KINDLE/, 'Kindle', '📚', 'Subscriptions'],
  [/APPLE\.COM\/BILL|APPLE\.COM BILL|ITUNES/, 'Apple', '', 'Subscriptions'],
  [/OPENAI|CHATGPT/, 'ChatGPT', '🤖', 'Subscriptions'],
  [/ANTHROPIC|CLAUDE\.AI/, 'Claude', '🤖', 'Subscriptions'],
  [/PATREON/, 'Patreon', '🎨', 'Subscriptions'],
  [/TWITCH/, 'Twitch', '🎮', 'Subscriptions'],
  [/DISCORD/, 'Discord', '🎮', 'Subscriptions'],
  [/DROPBOX/, 'Dropbox', '☁️', 'Subscriptions'],
  [/ICLOUD/, 'iCloud', '☁️', 'Subscriptions'],
  [/CANVA/, 'Canva', '🎨', 'Subscriptions'],
  [/ADOBE/, 'Adobe', '🎨', 'Subscriptions'],
  [/NYTIMES|NY TIMES/, 'NY Times', '📰', 'Subscriptions'],

  // Gaming
  [/STEAM\s*GAMES|STEAMGAMES|VALVE/, 'Steam', '🎮', 'Gaming'],
  [/PLAYSTATION|SONY INTERACTIVE/, 'PlayStation', '🎮', 'Gaming'],
  [/\bXBOX\b|MICROSOFT\s*\*?XBOX/, 'Xbox', '🎮', 'Gaming'],
  [/NINTENDO/, 'Nintendo', '🎮', 'Gaming'],
  [/EPIC GAMES/, 'Epic Games', '🎮', 'Gaming'],
  [/RIOT\s*GAMES|RIOT \*/, 'Riot Games', '🎮', 'Gaming'],

  // Transport / gas
  [/\bUBER\b(?!\s*\*?EATS)/, 'Uber', '🚗', 'Transport'],
  [/\bLYFT\b/, 'Lyft', '🚗', 'Transport'],
  [/SHELL OIL|SHELL SERVICE/, 'Shell', '⛽', 'Gas'],
  [/CHEVRON/, 'Chevron', '⛽', 'Gas'],
  [/EXXON|MOBIL\b/, 'ExxonMobil', '⛽', 'Gas'],
  [/\bBP\b|BP#|BP PRODUCTS/, 'BP', '⛽', 'Gas'],
  [/CASEY'?S/, "Casey's", '⛽', 'Gas'],
  [/SPEEDWAY/, 'Speedway', '⛽', 'Gas'],
  [/CIRCLE K/, 'Circle K', '⛽', 'Gas'],
  [/PARKING|PARKMOBILE|SPOTHERO/, 'Parking', '🅿️', 'Transport'],

  // Travel
  [/AIRBNB/, 'Airbnb', '🏡', 'Travel'],
  [/MARRIOTT/, 'Marriott', '🏨', 'Travel'],
  [/HILTON/, 'Hilton', '🏨', 'Travel'],
  [/DELTA AIR/, 'Delta', '✈️', 'Travel'],
  [/UNITED AIR|UNITED 016/, 'United Airlines', '✈️', 'Travel'],
  [/AMERICAN AIR|AMERICAN 001/, 'American Airlines', '✈️', 'Travel'],
  [/SOUTHWES?T/, 'Southwest', '✈️', 'Travel'],
  [/EXPEDIA/, 'Expedia', '✈️', 'Travel'],
  [/BOOKING\.COM/, 'Booking.com', '🏨', 'Travel'],

  // Entertainment
  [/TICKETMASTER/, 'Ticketmaster', '🎟️', 'Entertainment'],
  [/STUBHUB/, 'StubHub', '🎟️', 'Entertainment'],
  [/\bAMC\b/, 'AMC Theatres', '🍿', 'Entertainment'],
  [/REGAL CINEMA|REGAL ENTERTAINMENT/, 'Regal', '🍿', 'Entertainment'],
  [/FANDANGO/, 'Fandango', '🍿', 'Entertainment'],
  [/DAVE\s*&\s*BUSTER/, "Dave & Buster's", '🕹️', 'Entertainment'],
  [/TOPGOLF/, 'Topgolf', '⛳', 'Entertainment'],

  // Fitness / self-care
  [/PLANET FIT/, 'Planet Fitness', '💪', 'Fitness'],
  [/EQUINOX/, 'Equinox', '💪', 'Fitness'],
  [/CLASSPASS/, 'ClassPass', '💪', 'Fitness'],
  [/PELOTON/, 'Peloton', '💪', 'Fitness'],
  [/\bYMCA\b/, 'YMCA', '💪', 'Fitness'],
  [/ORANGETHEORY/, 'Orangetheory', '💪', 'Fitness'],
  [/MASSAGE ENVY/, 'Massage Envy', '💆', 'Self-care'],
  [/GREAT CLIPS|SUPERCUTS/, 'Haircut', '💇', 'Self-care'],

  // Money sent
  [/VENMO/, 'Venmo', '💸', 'Money sent'],
  [/CASH APP|CASHAPP|SQC\*/, 'Cash App', '💸', 'Money sent'],
  [/PAYPAL(?!\s*\*)/, 'PayPal', '💸', 'Money sent'],

  // Pets
  [/CHEWY/, 'Chewy', '🐾', 'Shopping'],
  [/PETSMART|PETCO/, 'Pet store', '🐾', 'Shopping'],
];

export const CATEGORY_EMOJI = {
  'Food delivery': '🛵',
  Restaurants: '🍽️',
  Coffee: '☕',
  Groceries: '🛒',
  Shopping: '🛍️',
  Subscriptions: '📺',
  Transport: '🚗',
  Gas: '⛽',
  Travel: '✈️',
  Entertainment: '🎟️',
  Fitness: '💪',
  'Self-care': '💅',
  Drinks: '🍻',
  Gaming: '🎮',
  'Money sent': '💸',
  Other: '🧾',
};
